pipeline:
  name: Ave Mundus
  identifier: Ave_Mundus
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712504098
        repoName: aedifex/avemundus
        build: <+input>
  stages:
    - stage:
        name: Run Tests
        identifier: Run_Tests
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Execute Tests
                  identifier: Execute_Tests
                  spec:
                    shell: Sh
                    command: go test -v
